# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc082ebf3ec458ac9876535d49454340735fa4b302498b8d6c557af57d169e60364f5d84fa8d394aafb6c7c85cfdfa8f39e7362ba225ef0722623bbbc3915e8f

test:
  secret_key_base: fa884edd229cea79928f0a93eea8dd3cabc7d933033cf17fccf3faba036fd83825386984e72f165ea9a083de5641ba3cf63aaedc48b55f4a1a6d718b4f317a0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
